export const API_URL = process.env.REACT_APP_API_URL;

export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS';
export const SESSION_LOGIN_FAILED = 'SESSION_LOGIN_FAILED';
export const SESSION_REGISTER_SUCCESS = 'SESSION_REGISTER_SUCCESS';
export const SESSION_REGISTER_FAILED = 'SESSION_REGISTER_FAILED';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SESSION_REQUEST_FAILED = 'SESSION_REQUEST_FAILED';
export const SESSION_REQUEST_FINISHED = 'SESSION_REQUEST_FINISHED';

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_EXECUTE_REQUEST = 'PAYMENT_EXECUTE_REQUEST';
export const PAYMENT_EXECUTE = 'PAYMENT_EXECUTE';
export const PAYMENT_INVOICE_SUCCESS = 'PAYMENT_INVOICE_SUCCESS';
export const PAYMENT_INVOICE_FAILED = 'PAYMENT_INVOICE_FAILED';

export const BETTING_HISTORY_REQUEST = 'BETTING_HISTORY_REQUEST';
export const BETTING_HISTORY_REQUEST_SUCCESS = 'BETTING_HISTORY_REQUEST_SUCCESS';
export const BETTING_HISTORY_REQUEST_FAILED = 'BETTING_HISTORY_REQUEST_FAILED';
export const CHECKING_NEWS = 'CHECKING_NEWS';

export const CREDENTIAL_REQUEST = 'CREDENTIAL_REQUEST';
export const CREDENTIAL_GET_REQUEST_SUCCESS = 'CREDENTIAL_GET_REQUEST_SUCCESS';
export const CREDENTIAL_ADD_REQUEST_SUCCESS = 'CREDENTIAL_ADD_REQUEST_SUCCESS';
export const CREDENTIAL_UPDATE_REQUEST_SUCCESS = 'CREDENTIAL_UPDATE_REQUEST_SUCCESS';
export const CREDENTIAL_DELETE_REQUEST_SUCCESS = 'CREDENTIAL_DELETE_REQUEST_SUCCESS';
export const CREDENTIAL_REQUEST_FAILED = 'CREDENTIAL_REQUEST_FAILED';

export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_GET_REQUEST_SUCCESS = 'NEWS_GET_REQUEST_SUCCESS';
export const NEWS_ADD_REQUEST_SUCCESS = 'NEWS_ADD_REQUEST_SUCCESS';
export const NEWS_UPDATE_REQUEST_SUCCESS = 'NEWS_UPDATE_REQUEST_SUCCESS';
export const NEWS_DELETE_REQUEST_SUCCESS = 'NEWS_DELETE_REQUEST_SUCCESS';
export const NEWS_REQUEST_FAILED = 'NEWS_REQUEST_FAILED';

export const SUPPORT_REQUEST = 'SUPPORT_REQUEST';
export const SUPPORT_GET_REQUEST_SUCCESS = 'SUPPORT_GET_REQUEST_SUCCESS';
export const SUPPORT_UPDATE_REQUEST_SUCCESS = 'SUPPORT_UPDATE_REQUEST_SUCCESS';
export const SUPPORT_REQUEST_FAILED = 'SUPPORT_REQUEST_FAILED';

export const TICKET_REQUEST = 'TICKET_REQUEST';
export const TICKET_GET_REQUEST_SUCCESS = 'TICKET_GET_REQUEST_SUCCESS';
export const TICKET_ADD_REQUEST_SUCCESS = 'TICKET_ADD_REQUEST_SUCCESS';
export const TICKET_UPDATE_REQUEST_SUCCESS = 'TICKET_UPDATE_REQUEST_SUCCESS';
export const TICKET_DELETE_REQUEST_SUCCESS = 'TICKET_DELETE_REQUEST_SUCCESS';
export const TICKET_REQUEST_FAILED = 'TICKET_REQUEST_FAILED';

export const MESSAGE_REQUEST = 'MESSAGE_REQUEST';
export const MESSAGE_GET_REQUEST_SUCCESS = 'MESSAGE_GET_REQUEST_SUCCESS';
export const MESSAGE_SEND_REQUEST_SUCCESS = 'MESSAGE_ADD_REQUEST_SUCCESS';
export const MESSAGE_REQUEST_FAILED = 'MESSAGE_REQUEST_FAILED';

export const countryList = {
  "AR": "Argentina",
  "BE": "Belgium",
  "BR": "Brazil",
  "BD": "Bangladesh",
  "CL": "Chile",
  "DK": "Denmark",
  "EG": "Egypt",
  "FR": "France",
  "GB": "Great Britain",
  "DE": "Germany",
  "GR": "Greece",
  "IN": "India",
  "IT": "Italy",
  "MX": "Mexico",
  "NL": "Netherlands",
  "PE": "Peru",
  "RU": "Russia",
  "ZA": "South Africa",
  "ES": "Spain",
  "UA": "Ukraine"
};
